version: '3.1'

services:
  jrtb-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_jrtb_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ibiigor4954'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'ibiigor4954'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '80:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'